spring:
  application:
    name: MySpringBoot2Dbase
  datasource:
    url: jdbc:h2:/testdb/students
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port:  8082
